<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="21" failed="0" ignored="0" total="21" passed="0">
  <reporter-output>
  </reporter-output>
  <suite name="Default suite" duration-ms="225" started-at="2018-05-08T12:27:13Z" finished-at="2018-05-08T12:27:13Z">
    <groups>
    </groups>
    <test name="Default test" duration-ms="225" started-at="2018-05-08T12:27:13Z" finished-at="2018-05-08T12:27:13Z">
      <class name="email_module_test_cases.MaropostEmailContactsTestCases">
        <test-method status="FAIL" signature="setup()[pri:0, instance:email_module_test_cases.MaropostEmailContactsTestCases@161b062a]" name="setup" is-config="true" duration-ms="15520" started-at="2018-05-08T17:56:57Z" finished-at="2018-05-08T17:57:13Z">
          <exception class="org.openqa.selenium.WebDriverException">
            <message>
              <![CDATA[timeoutsBuild info: version: 'unknown', revision: 'unknown', time: 'unknown'System info: host: '173-168-101-239.res.bhn.net', ip: '173.168.101.239', os.name: 'Mac OS X', os.arch: 'x86_64', os.version: '10.12.6', java.version: '1.8.0_131'Driver info: org.openqa.selenium.firefox.FirefoxDriverCapabilities [{moz:profile=/var/folders/vp/4tv7xm2s0q15kxssvqx4dtl40000gn/T/rust_mozprofile.vllH6tdRwV4U, rotatable=false, timeouts={implicit=0.0, pageLoad=300000.0, script=30000.0}, pageLoadStrategy=normal, moz:headless=false, platform=ANY, moz:accessibilityChecks=false, moz:useNonSpecCompliantPointerOrigin=false, acceptInsecureCerts=false, browserVersion=59.0.2, platformVersion=16.7.0, moz:processID=2009.0, browserName=firefox, javascriptEnabled=true, platformName=darwin, moz:webdriverClick=true}]Session ID: dafa1031-f118-d949-bf1b-44a6946a1b91]]>
            </message>
            <full-stacktrace>
              <![CDATA[org.openqa.selenium.WebDriverException: timeoutsBuild info: version: 'unknown', revision: 'unknown', time: 'unknown'System info: host: '173-168-101-239.res.bhn.net', ip: '173.168.101.239', os.name: 'Mac OS X', os.arch: 'x86_64', os.version: '10.12.6', java.version: '1.8.0_131'Driver info: org.openqa.selenium.firefox.FirefoxDriverCapabilities [{moz:profile=/var/folders/vp/4tv7xm2s0q15kxssvqx4dtl40000gn/T/rust_mozprofile.vllH6tdRwV4U, rotatable=false, timeouts={implicit=0.0, pageLoad=300000.0, script=30000.0}, pageLoadStrategy=normal, moz:headless=false, platform=ANY, moz:accessibilityChecks=false, moz:useNonSpecCompliantPointerOrigin=false, acceptInsecureCerts=false, browserVersion=59.0.2, platformVersion=16.7.0, moz:processID=2009.0, browserName=firefox, javascriptEnabled=true, platformName=darwin, moz:webdriverClick=true}]Session ID: dafa1031-f118-d949-bf1b-44a6946a1b91at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)at java.lang.reflect.Constructor.newInstance(Constructor.java:423)at org.openqa.selenium.remote.http.W3CHttpResponseCodec.createException(W3CHttpResponseCodec.java:150)at org.openqa.selenium.remote.http.W3CHttpResponseCodec.decode(W3CHttpResponseCodec.java:115)at org.openqa.selenium.remote.http.W3CHttpResponseCodec.decode(W3CHttpResponseCodec.java:45)at org.openqa.selenium.remote.HttpCommandExecutor.execute(HttpCommandExecutor.java:164)at org.openqa.selenium.remote.service.DriverCommandExecutor.execute(DriverCommandExecutor.java:82)at org.openqa.selenium.remote.RemoteWebDriver.execute(RemoteWebDriver.java:637)at org.openqa.selenium.remote.RemoteWebDriver$RemoteWebDriverOptions$RemoteTimeouts.implicitlyWait(RemoteWebDriver.java:868)at email_module_test_cases.MaropostEmailContactsTestCases.setup(MaropostEmailContactsTestCases.java:38)at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)at java.lang.reflect.Method.invoke(Method.java:498)at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)at org.testng.internal.MethodInvocationHelper.invokeMethodConsideringTimeout(MethodInvocationHelper.java:59)at org.testng.internal.Invoker.invokeConfigurationMethod(Invoker.java:451)at org.testng.internal.Invoker.invokeConfigurations(Invoker.java:222)at org.testng.internal.Invoker.invokeConfigurations(Invoker.java:142)at org.testng.SuiteRunner.privateRun(SuiteRunner.java:401)at org.testng.SuiteRunner.run(SuiteRunner.java:364)at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)at org.testng.TestNG.runSuitesSequentially(TestNG.java:1187)at org.testng.TestNG.runSuitesLocally(TestNG.java:1116)at org.testng.TestNG.runSuites(TestNG.java:1028)at org.testng.TestNG.run(TestNG.java:996)at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)]]>
            </full-stacktrace>
          </exception> <!-- org.openqa.selenium.WebDriverException -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setup -->
        <test-method status="SKIP" signature="test_verify_signin_section()[pri:0, instance:email_module_test_cases.MaropostEmailContactsTestCases@161b062a]" name="test_verify_signin_section" duration-ms="0" started-at="2018-05-08T17:57:13Z" finished-at="2018-05-08T17:57:13Z">
          <exception class="org.openqa.selenium.WebDriverException">
            <message>
              <![CDATA[timeoutsBuild info: version: 'unknown', revision: 'unknown', time: 'unknown'System info: host: '173-168-101-239.res.bhn.net', ip: '173.168.101.239', os.name: 'Mac OS X', os.arch: 'x86_64', os.version: '10.12.6', java.version: '1.8.0_131'Driver info: org.openqa.selenium.firefox.FirefoxDriverCapabilities [{moz:profile=/var/folders/vp/4tv7xm2s0q15kxssvqx4dtl40000gn/T/rust_mozprofile.vllH6tdRwV4U, rotatable=false, timeouts={implicit=0.0, pageLoad=300000.0, script=30000.0}, pageLoadStrategy=normal, moz:headless=false, platform=ANY, moz:accessibilityChecks=false, moz:useNonSpecCompliantPointerOrigin=false, acceptInsecureCerts=false, browserVersion=59.0.2, platformVersion=16.7.0, moz:processID=2009.0, browserName=firefox, javascriptEnabled=true, platformName=darwin, moz:webdriverClick=true}]Session ID: dafa1031-f118-d949-bf1b-44a6946a1b91]]>
            </message>
            <full-stacktrace>
              <![CDATA[org.openqa.selenium.WebDriverException: timeoutsBuild info: version: 'unknown', revision: 'unknown', time: 'unknown'System info: host: '173-168-101-239.res.bhn.net', ip: '173.168.101.239', os.name: 'Mac OS X', os.arch: 'x86_64', os.version: '10.12.6', java.version: '1.8.0_131'Driver info: org.openqa.selenium.firefox.FirefoxDriverCapabilities [{moz:profile=/var/folders/vp/4tv7xm2s0q15kxssvqx4dtl40000gn/T/rust_mozprofile.vllH6tdRwV4U, rotatable=false, timeouts={implicit=0.0, pageLoad=300000.0, script=30000.0}, pageLoadStrategy=normal, moz:headless=false, platform=ANY, moz:accessibilityChecks=false, moz:useNonSpecCompliantPointerOrigin=false, acceptInsecureCerts=false, browserVersion=59.0.2, platformVersion=16.7.0, moz:processID=2009.0, browserName=firefox, javascriptEnabled=true, platformName=darwin, moz:webdriverClick=true}]Session ID: dafa1031-f118-d949-bf1b-44a6946a1b91at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)at java.lang.reflect.Constructor.newInstance(Constructor.java:423)at org.openqa.selenium.remote.http.W3CHttpResponseCodec.createException(W3CHttpResponseCodec.java:150)at org.openqa.selenium.remote.http.W3CHttpResponseCodec.decode(W3CHttpResponseCodec.java:115)at org.openqa.selenium.remote.http.W3CHttpResponseCodec.decode(W3CHttpResponseCodec.java:45)at org.openqa.selenium.remote.HttpCommandExecutor.execute(HttpCommandExecutor.java:164)at org.openqa.selenium.remote.service.DriverCommandExecutor.execute(DriverCommandExecutor.java:82)at org.openqa.selenium.remote.RemoteWebDriver.execute(RemoteWebDriver.java:637)at org.openqa.selenium.remote.RemoteWebDriver$RemoteWebDriverOptions$RemoteTimeouts.implicitlyWait(RemoteWebDriver.java:868)at email_module_test_cases.MaropostEmailContactsTestCases.setup(MaropostEmailContactsTestCases.java:38)at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)at java.lang.reflect.Method.invoke(Method.java:498)at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)at org.testng.internal.MethodInvocationHelper.invokeMethodConsideringTimeout(MethodInvocationHelper.java:59)at org.testng.internal.Invoker.invokeConfigurationMethod(Invoker.java:451)at org.testng.internal.Invoker.invokeConfigurations(Invoker.java:222)at org.testng.internal.Invoker.invokeConfigurations(Invoker.java:142)at org.testng.SuiteRunner.privateRun(SuiteRunner.java:401)at org.testng.SuiteRunner.run(SuiteRunner.java:364)at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)at org.testng.TestNG.runSuitesSequentially(TestNG.java:1187)at org.testng.TestNG.runSuitesLocally(TestNG.java:1116)at org.testng.TestNG.runSuites(TestNG.java:1028)at org.testng.TestNG.run(TestNG.java:996)at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)]]>
            </full-stacktrace>
          </exception> <!-- org.openqa.selenium.WebDriverException -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- test_verify_signin_section -->
        <test-method status="SKIP" signature="test_create_new_contacts_list()[pri:0, instance:email_module_test_cases.MaropostEmailContactsTestCases@161b062a]" name="test_create_new_contacts_list" duration-ms="0" started-at="2018-05-08T17:57:13Z" depends-on-methods="email_module_test_cases.MaropostEmailContactsTestCases.test_verify_signin_section" finished-at="2018-05-08T17:57:13Z">
          <exception class="java.lang.Throwable">
            <message>
              <![CDATA[Method MaropostEmailContactsTestCases.test_create_new_contacts_list()[pri:0, instance:email_module_test_cases.MaropostEmailContactsTestCases@161b062a] depends on not successfully finished methods]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.Throwable: Method MaropostEmailContactsTestCases.test_create_new_contacts_list()[pri:0, instance:email_module_test_cases.MaropostEmailContactsTestCases@161b062a] depends on not successfully finished methodsat org.testng.internal.Invoker.invokeTestMethods(Invoker.java:878)at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)at org.testng.TestRunner.privateRun(TestRunner.java:648)at org.testng.TestRunner.run(TestRunner.java:505)at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)at org.testng.SuiteRunner.run(SuiteRunner.java:364)at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)at org.testng.TestNG.runSuitesSequentially(TestNG.java:1187)at org.testng.TestNG.runSuitesLocally(TestNG.java:1116)at org.testng.TestNG.runSuites(TestNG.java:1028)at org.testng.TestNG.run(TestNG.java:996)at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)]]>
            </full-stacktrace>
          </exception> <!-- java.lang.Throwable -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- test_create_new_contacts_list -->
        <test-method status="SKIP" signature="test_to_edit_contacts_list()[pri:0, instance:email_module_test_cases.MaropostEmailContactsTestCases@161b062a]" name="test_to_edit_contacts_list" duration-ms="0" started-at="2018-05-08T17:57:13Z" depends-on-methods="email_module_test_cases.MaropostEmailContactsTestCases.test_create_new_contacts_list" finished-at="2018-05-08T17:57:13Z">
          <exception class="java.lang.Throwable">
            <message>
              <![CDATA[Method MaropostEmailContactsTestCases.test_to_edit_contacts_list()[pri:0, instance:email_module_test_cases.MaropostEmailContactsTestCases@161b062a] depends on not successfully finished methods]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.Throwable: Method MaropostEmailContactsTestCases.test_to_edit_contacts_list()[pri:0, instance:email_module_test_cases.MaropostEmailContactsTestCases@161b062a] depends on not successfully finished methodsat org.testng.internal.Invoker.invokeTestMethods(Invoker.java:878)at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)at org.testng.TestRunner.privateRun(TestRunner.java:648)at org.testng.TestRunner.run(TestRunner.java:505)at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)at org.testng.SuiteRunner.run(SuiteRunner.java:364)at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)at org.testng.TestNG.runSuitesSequentially(TestNG.java:1187)at org.testng.TestNG.runSuitesLocally(TestNG.java:1116)at org.testng.TestNG.runSuites(TestNG.java:1028)at org.testng.TestNG.run(TestNG.java:996)at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)]]>
            </full-stacktrace>
          </exception> <!-- java.lang.Throwable -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- test_to_edit_contacts_list -->
        <test-method status="SKIP" signature="test_to_delete_contacts_list()[pri:0, instance:email_module_test_cases.MaropostEmailContactsTestCases@161b062a]" name="test_to_delete_contacts_list" duration-ms="0" started-at="2018-05-08T17:57:13Z" depends-on-methods="email_module_test_cases.MaropostEmailContactsTestCases.test_to_edit_contacts_list" finished-at="2018-05-08T17:57:13Z">
          <exception class="java.lang.Throwable">
            <message>
              <![CDATA[Method MaropostEmailContactsTestCases.test_to_delete_contacts_list()[pri:0, instance:email_module_test_cases.MaropostEmailContactsTestCases@161b062a] depends on not successfully finished methods]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.Throwable: Method MaropostEmailContactsTestCases.test_to_delete_contacts_list()[pri:0, instance:email_module_test_cases.MaropostEmailContactsTestCases@161b062a] depends on not successfully finished methodsat org.testng.internal.Invoker.invokeTestMethods(Invoker.java:878)at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)at org.testng.TestRunner.privateRun(TestRunner.java:648)at org.testng.TestRunner.run(TestRunner.java:505)at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)at org.testng.SuiteRunner.run(SuiteRunner.java:364)at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)at org.testng.TestNG.runSuitesSequentially(TestNG.java:1187)at org.testng.TestNG.runSuitesLocally(TestNG.java:1116)at org.testng.TestNG.runSuites(TestNG.java:1028)at org.testng.TestNG.run(TestNG.java:996)at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)]]>
            </full-stacktrace>
          </exception> <!-- java.lang.Throwable -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- test_to_delete_contacts_list -->
        <test-method status="SKIP" signature="test_create_new_contacts_field()[pri:0, instance:email_module_test_cases.MaropostEmailContactsTestCases@161b062a]" name="test_create_new_contacts_field" duration-ms="0" started-at="2018-05-08T17:57:13Z" depends-on-methods="email_module_test_cases.MaropostEmailContactsTestCases.test_to_delete_contacts_list" finished-at="2018-05-08T17:57:13Z">
          <exception class="java.lang.Throwable">
            <message>
              <![CDATA[Method MaropostEmailContactsTestCases.test_create_new_contacts_field()[pri:0, instance:email_module_test_cases.MaropostEmailContactsTestCases@161b062a] depends on not successfully finished methods]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.Throwable: Method MaropostEmailContactsTestCases.test_create_new_contacts_field()[pri:0, instance:email_module_test_cases.MaropostEmailContactsTestCases@161b062a] depends on not successfully finished methodsat org.testng.internal.Invoker.invokeTestMethods(Invoker.java:878)at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)at org.testng.TestRunner.privateRun(TestRunner.java:648)at org.testng.TestRunner.run(TestRunner.java:505)at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)at org.testng.SuiteRunner.run(SuiteRunner.java:364)at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)at org.testng.TestNG.runSuitesSequentially(TestNG.java:1187)at org.testng.TestNG.runSuitesLocally(TestNG.java:1116)at org.testng.TestNG.runSuites(TestNG.java:1028)at org.testng.TestNG.run(TestNG.java:996)at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)]]>
            </full-stacktrace>
          </exception> <!-- java.lang.Throwable -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- test_create_new_contacts_field -->
        <test-method status="SKIP" signature="test_create_new_contacts_tag()[pri:0, instance:email_module_test_cases.MaropostEmailContactsTestCases@161b062a]" name="test_create_new_contacts_tag" duration-ms="0" started-at="2018-05-08T17:57:13Z" depends-on-methods="email_module_test_cases.MaropostEmailContactsTestCases.test_create_new_contacts_field" finished-at="2018-05-08T17:57:13Z">
          <exception class="java.lang.Throwable">
            <message>
              <![CDATA[Method MaropostEmailContactsTestCases.test_create_new_contacts_tag()[pri:0, instance:email_module_test_cases.MaropostEmailContactsTestCases@161b062a] depends on not successfully finished methods]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.Throwable: Method MaropostEmailContactsTestCases.test_create_new_contacts_tag()[pri:0, instance:email_module_test_cases.MaropostEmailContactsTestCases@161b062a] depends on not successfully finished methodsat org.testng.internal.Invoker.invokeTestMethods(Invoker.java:878)at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)at org.testng.TestRunner.privateRun(TestRunner.java:648)at org.testng.TestRunner.run(TestRunner.java:505)at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)at org.testng.SuiteRunner.run(SuiteRunner.java:364)at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)at org.testng.TestNG.runSuitesSequentially(TestNG.java:1187)at org.testng.TestNG.runSuitesLocally(TestNG.java:1116)at org.testng.TestNG.runSuites(TestNG.java:1028)at org.testng.TestNG.run(TestNG.java:996)at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)]]>
            </full-stacktrace>
          </exception> <!-- java.lang.Throwable -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- test_create_new_contacts_tag -->
        <test-method status="SKIP" signature="test_to_delete_contacts_tag()[pri:0, instance:email_module_test_cases.MaropostEmailContactsTestCases@161b062a]" name="test_to_delete_contacts_tag" duration-ms="0" started-at="2018-05-08T17:57:13Z" depends-on-methods="email_module_test_cases.MaropostEmailContactsTestCases.test_create_new_contacts_tag" finished-at="2018-05-08T17:57:13Z">
          <exception class="java.lang.Throwable">
            <message>
              <![CDATA[Method MaropostEmailContactsTestCases.test_to_delete_contacts_tag()[pri:0, instance:email_module_test_cases.MaropostEmailContactsTestCases@161b062a] depends on not successfully finished methods]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.Throwable: Method MaropostEmailContactsTestCases.test_to_delete_contacts_tag()[pri:0, instance:email_module_test_cases.MaropostEmailContactsTestCases@161b062a] depends on not successfully finished methodsat org.testng.internal.Invoker.invokeTestMethods(Invoker.java:878)at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)at org.testng.TestRunner.privateRun(TestRunner.java:648)at org.testng.TestRunner.run(TestRunner.java:505)at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)at org.testng.SuiteRunner.run(SuiteRunner.java:364)at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)at org.testng.TestNG.runSuitesSequentially(TestNG.java:1187)at org.testng.TestNG.runSuitesLocally(TestNG.java:1116)at org.testng.TestNG.runSuites(TestNG.java:1028)at org.testng.TestNG.run(TestNG.java:996)at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)]]>
            </full-stacktrace>
          </exception> <!-- java.lang.Throwable -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- test_to_delete_contacts_tag -->
        <test-method status="SKIP" signature="test_create_new_contacts_brand()[pri:0, instance:email_module_test_cases.MaropostEmailContactsTestCases@161b062a]" name="test_create_new_contacts_brand" duration-ms="0" started-at="2018-05-08T17:57:13Z" depends-on-methods="email_module_test_cases.MaropostEmailContactsTestCases.test_to_delete_contacts_tag" finished-at="2018-05-08T17:57:13Z">
          <exception class="java.lang.Throwable">
            <message>
              <![CDATA[Method MaropostEmailContactsTestCases.test_create_new_contacts_brand()[pri:0, instance:email_module_test_cases.MaropostEmailContactsTestCases@161b062a] depends on not successfully finished methods]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.Throwable: Method MaropostEmailContactsTestCases.test_create_new_contacts_brand()[pri:0, instance:email_module_test_cases.MaropostEmailContactsTestCases@161b062a] depends on not successfully finished methodsat org.testng.internal.Invoker.invokeTestMethods(Invoker.java:878)at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)at org.testng.TestRunner.privateRun(TestRunner.java:648)at org.testng.TestRunner.run(TestRunner.java:505)at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)at org.testng.SuiteRunner.run(SuiteRunner.java:364)at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)at org.testng.TestNG.runSuitesSequentially(TestNG.java:1187)at org.testng.TestNG.runSuitesLocally(TestNG.java:1116)at org.testng.TestNG.runSuites(TestNG.java:1028)at org.testng.TestNG.run(TestNG.java:996)at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)]]>
            </full-stacktrace>
          </exception> <!-- java.lang.Throwable -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- test_create_new_contacts_brand -->
        <test-method status="SKIP" signature="test_to_edit_contacts_brand()[pri:0, instance:email_module_test_cases.MaropostEmailContactsTestCases@161b062a]" name="test_to_edit_contacts_brand" duration-ms="0" started-at="2018-05-08T17:57:13Z" depends-on-methods="email_module_test_cases.MaropostEmailContactsTestCases.test_create_new_contacts_brand" finished-at="2018-05-08T17:57:13Z">
          <exception class="java.lang.Throwable">
            <message>
              <![CDATA[Method MaropostEmailContactsTestCases.test_to_edit_contacts_brand()[pri:0, instance:email_module_test_cases.MaropostEmailContactsTestCases@161b062a] depends on not successfully finished methods]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.Throwable: Method MaropostEmailContactsTestCases.test_to_edit_contacts_brand()[pri:0, instance:email_module_test_cases.MaropostEmailContactsTestCases@161b062a] depends on not successfully finished methodsat org.testng.internal.Invoker.invokeTestMethods(Invoker.java:878)at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)at org.testng.TestRunner.privateRun(TestRunner.java:648)at org.testng.TestRunner.run(TestRunner.java:505)at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)at org.testng.SuiteRunner.run(SuiteRunner.java:364)at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)at org.testng.TestNG.runSuitesSequentially(TestNG.java:1187)at org.testng.TestNG.runSuitesLocally(TestNG.java:1116)at org.testng.TestNG.runSuites(TestNG.java:1028)at org.testng.TestNG.run(TestNG.java:996)at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)]]>
            </full-stacktrace>
          </exception> <!-- java.lang.Throwable -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- test_to_edit_contacts_brand -->
        <test-method status="SKIP" signature="test_create_new_contacts_secure_list()[pri:0, instance:email_module_test_cases.MaropostEmailContactsTestCases@161b062a]" name="test_create_new_contacts_secure_list" duration-ms="0" started-at="2018-05-08T17:57:13Z" depends-on-methods="email_module_test_cases.MaropostEmailContactsTestCases.test_to_edit_contacts_brand" finished-at="2018-05-08T17:57:13Z">
          <exception class="java.lang.Throwable">
            <message>
              <![CDATA[Method MaropostEmailContactsTestCases.test_create_new_contacts_secure_list()[pri:0, instance:email_module_test_cases.MaropostEmailContactsTestCases@161b062a] depends on not successfully finished methods]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.Throwable: Method MaropostEmailContactsTestCases.test_create_new_contacts_secure_list()[pri:0, instance:email_module_test_cases.MaropostEmailContactsTestCases@161b062a] depends on not successfully finished methodsat org.testng.internal.Invoker.invokeTestMethods(Invoker.java:878)at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)at org.testng.TestRunner.privateRun(TestRunner.java:648)at org.testng.TestRunner.run(TestRunner.java:505)at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)at org.testng.SuiteRunner.run(SuiteRunner.java:364)at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)at org.testng.TestNG.runSuitesSequentially(TestNG.java:1187)at org.testng.TestNG.runSuitesLocally(TestNG.java:1116)at org.testng.TestNG.runSuites(TestNG.java:1028)at org.testng.TestNG.run(TestNG.java:996)at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)]]>
            </full-stacktrace>
          </exception> <!-- java.lang.Throwable -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- test_create_new_contacts_secure_list -->
        <test-method status="SKIP" signature="test_to_edit_contacts_secure_list()[pri:0, instance:email_module_test_cases.MaropostEmailContactsTestCases@161b062a]" name="test_to_edit_contacts_secure_list" duration-ms="0" started-at="2018-05-08T17:57:13Z" depends-on-methods="email_module_test_cases.MaropostEmailContactsTestCases.test_create_new_contacts_secure_list" finished-at="2018-05-08T17:57:13Z">
          <exception class="java.lang.Throwable">
            <message>
              <![CDATA[Method MaropostEmailContactsTestCases.test_to_edit_contacts_secure_list()[pri:0, instance:email_module_test_cases.MaropostEmailContactsTestCases@161b062a] depends on not successfully finished methods]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.Throwable: Method MaropostEmailContactsTestCases.test_to_edit_contacts_secure_list()[pri:0, instance:email_module_test_cases.MaropostEmailContactsTestCases@161b062a] depends on not successfully finished methodsat org.testng.internal.Invoker.invokeTestMethods(Invoker.java:878)at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)at org.testng.TestRunner.privateRun(TestRunner.java:648)at org.testng.TestRunner.run(TestRunner.java:505)at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)at org.testng.SuiteRunner.run(SuiteRunner.java:364)at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)at org.testng.TestNG.runSuitesSequentially(TestNG.java:1187)at org.testng.TestNG.runSuitesLocally(TestNG.java:1116)at org.testng.TestNG.runSuites(TestNG.java:1028)at org.testng.TestNG.run(TestNG.java:996)at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)]]>
            </full-stacktrace>
          </exception> <!-- java.lang.Throwable -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- test_to_edit_contacts_secure_list -->
        <test-method status="SKIP" signature="test_create_new_contacts_table()[pri:0, instance:email_module_test_cases.MaropostEmailContactsTestCases@161b062a]" name="test_create_new_contacts_table" duration-ms="0" started-at="2018-05-08T17:57:13Z" depends-on-methods="email_module_test_cases.MaropostEmailContactsTestCases.test_to_edit_contacts_secure_list" finished-at="2018-05-08T17:57:13Z">
          <exception class="java.lang.Throwable">
            <message>
              <![CDATA[Method MaropostEmailContactsTestCases.test_create_new_contacts_table()[pri:0, instance:email_module_test_cases.MaropostEmailContactsTestCases@161b062a] depends on not successfully finished methods]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.Throwable: Method MaropostEmailContactsTestCases.test_create_new_contacts_table()[pri:0, instance:email_module_test_cases.MaropostEmailContactsTestCases@161b062a] depends on not successfully finished methodsat org.testng.internal.Invoker.invokeTestMethods(Invoker.java:878)at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)at org.testng.TestRunner.privateRun(TestRunner.java:648)at org.testng.TestRunner.run(TestRunner.java:505)at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)at org.testng.SuiteRunner.run(SuiteRunner.java:364)at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)at org.testng.TestNG.runSuitesSequentially(TestNG.java:1187)at org.testng.TestNG.runSuitesLocally(TestNG.java:1116)at org.testng.TestNG.runSuites(TestNG.java:1028)at org.testng.TestNG.run(TestNG.java:996)at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)]]>
            </full-stacktrace>
          </exception> <!-- java.lang.Throwable -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- test_create_new_contacts_table -->
        <test-method status="SKIP" signature="test_to_delete_contacts_securelist()[pri:0, instance:email_module_test_cases.MaropostEmailContactsTestCases@161b062a]" name="test_to_delete_contacts_securelist" duration-ms="0" started-at="2018-05-08T17:57:13Z" depends-on-methods="email_module_test_cases.MaropostEmailContactsTestCases.test_to_edit_contacts_secure_list" finished-at="2018-05-08T17:57:13Z">
          <exception class="java.lang.Throwable">
            <message>
              <![CDATA[Method MaropostEmailContactsTestCases.test_to_delete_contacts_securelist()[pri:0, instance:email_module_test_cases.MaropostEmailContactsTestCases@161b062a] depends on not successfully finished methods]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.Throwable: Method MaropostEmailContactsTestCases.test_to_delete_contacts_securelist()[pri:0, instance:email_module_test_cases.MaropostEmailContactsTestCases@161b062a] depends on not successfully finished methodsat org.testng.internal.Invoker.invokeTestMethods(Invoker.java:878)at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)at org.testng.TestRunner.privateRun(TestRunner.java:648)at org.testng.TestRunner.run(TestRunner.java:505)at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)at org.testng.SuiteRunner.run(SuiteRunner.java:364)at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)at org.testng.TestNG.runSuitesSequentially(TestNG.java:1187)at org.testng.TestNG.runSuitesLocally(TestNG.java:1116)at org.testng.TestNG.runSuites(TestNG.java:1028)at org.testng.TestNG.run(TestNG.java:996)at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)]]>
            </full-stacktrace>
          </exception> <!-- java.lang.Throwable -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- test_to_delete_contacts_securelist -->
        <test-method status="SKIP" signature="test_to_edit_contacts_table()[pri:0, instance:email_module_test_cases.MaropostEmailContactsTestCases@161b062a]" name="test_to_edit_contacts_table" duration-ms="0" started-at="2018-05-08T17:57:13Z" depends-on-methods="email_module_test_cases.MaropostEmailContactsTestCases.test_create_new_contacts_table" finished-at="2018-05-08T17:57:13Z">
          <exception class="java.lang.Throwable">
            <message>
              <![CDATA[Method MaropostEmailContactsTestCases.test_to_edit_contacts_table()[pri:0, instance:email_module_test_cases.MaropostEmailContactsTestCases@161b062a] depends on not successfully finished methods]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.Throwable: Method MaropostEmailContactsTestCases.test_to_edit_contacts_table()[pri:0, instance:email_module_test_cases.MaropostEmailContactsTestCases@161b062a] depends on not successfully finished methodsat org.testng.internal.Invoker.invokeTestMethods(Invoker.java:878)at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)at org.testng.TestRunner.privateRun(TestRunner.java:648)at org.testng.TestRunner.run(TestRunner.java:505)at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)at org.testng.SuiteRunner.run(SuiteRunner.java:364)at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)at org.testng.TestNG.runSuitesSequentially(TestNG.java:1187)at org.testng.TestNG.runSuitesLocally(TestNG.java:1116)at org.testng.TestNG.runSuites(TestNG.java:1028)at org.testng.TestNG.run(TestNG.java:996)at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)]]>
            </full-stacktrace>
          </exception> <!-- java.lang.Throwable -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- test_to_edit_contacts_table -->
        <test-method status="SKIP" signature="test_to_delete_contacts_table()[pri:0, instance:email_module_test_cases.MaropostEmailContactsTestCases@161b062a]" name="test_to_delete_contacts_table" duration-ms="0" started-at="2018-05-08T17:57:13Z" depends-on-methods="email_module_test_cases.MaropostEmailContactsTestCases.test_to_edit_contacts_table" finished-at="2018-05-08T17:57:13Z">
          <exception class="java.lang.Throwable">
            <message>
              <![CDATA[Method MaropostEmailContactsTestCases.test_to_delete_contacts_table()[pri:0, instance:email_module_test_cases.MaropostEmailContactsTestCases@161b062a] depends on not successfully finished methods]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.Throwable: Method MaropostEmailContactsTestCases.test_to_delete_contacts_table()[pri:0, instance:email_module_test_cases.MaropostEmailContactsTestCases@161b062a] depends on not successfully finished methodsat org.testng.internal.Invoker.invokeTestMethods(Invoker.java:878)at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)at org.testng.TestRunner.privateRun(TestRunner.java:648)at org.testng.TestRunner.run(TestRunner.java:505)at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)at org.testng.SuiteRunner.run(SuiteRunner.java:364)at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)at org.testng.TestNG.runSuitesSequentially(TestNG.java:1187)at org.testng.TestNG.runSuitesLocally(TestNG.java:1116)at org.testng.TestNG.runSuites(TestNG.java:1028)at org.testng.TestNG.run(TestNG.java:996)at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)]]>
            </full-stacktrace>
          </exception> <!-- java.lang.Throwable -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- test_to_delete_contacts_table -->
        <test-method status="SKIP" signature="test_create_new_contacts_sqlquery()[pri:0, instance:email_module_test_cases.MaropostEmailContactsTestCases@161b062a]" name="test_create_new_contacts_sqlquery" duration-ms="0" started-at="2018-05-08T17:57:13Z" depends-on-methods="email_module_test_cases.MaropostEmailContactsTestCases.test_to_delete_contacts_table" finished-at="2018-05-08T17:57:13Z">
          <exception class="java.lang.Throwable">
            <message>
              <![CDATA[Method MaropostEmailContactsTestCases.test_create_new_contacts_sqlquery()[pri:0, instance:email_module_test_cases.MaropostEmailContactsTestCases@161b062a] depends on not successfully finished methods]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.Throwable: Method MaropostEmailContactsTestCases.test_create_new_contacts_sqlquery()[pri:0, instance:email_module_test_cases.MaropostEmailContactsTestCases@161b062a] depends on not successfully finished methodsat org.testng.internal.Invoker.invokeTestMethods(Invoker.java:878)at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)at org.testng.TestRunner.privateRun(TestRunner.java:648)at org.testng.TestRunner.run(TestRunner.java:505)at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)at org.testng.SuiteRunner.run(SuiteRunner.java:364)at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)at org.testng.TestNG.runSuitesSequentially(TestNG.java:1187)at org.testng.TestNG.runSuitesLocally(TestNG.java:1116)at org.testng.TestNG.runSuites(TestNG.java:1028)at org.testng.TestNG.run(TestNG.java:996)at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)]]>
            </full-stacktrace>
          </exception> <!-- java.lang.Throwable -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- test_create_new_contacts_sqlquery -->
        <test-method status="SKIP" signature="test_to_edit_contacts_sql_query()[pri:0, instance:email_module_test_cases.MaropostEmailContactsTestCases@161b062a]" name="test_to_edit_contacts_sql_query" duration-ms="0" started-at="2018-05-08T17:57:13Z" depends-on-methods="email_module_test_cases.MaropostEmailContactsTestCases.test_create_new_contacts_sqlquery" finished-at="2018-05-08T17:57:13Z">
          <exception class="java.lang.Throwable">
            <message>
              <![CDATA[Method MaropostEmailContactsTestCases.test_to_edit_contacts_sql_query()[pri:0, instance:email_module_test_cases.MaropostEmailContactsTestCases@161b062a] depends on not successfully finished methods]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.Throwable: Method MaropostEmailContactsTestCases.test_to_edit_contacts_sql_query()[pri:0, instance:email_module_test_cases.MaropostEmailContactsTestCases@161b062a] depends on not successfully finished methodsat org.testng.internal.Invoker.invokeTestMethods(Invoker.java:878)at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)at org.testng.TestRunner.privateRun(TestRunner.java:648)at org.testng.TestRunner.run(TestRunner.java:505)at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)at org.testng.SuiteRunner.run(SuiteRunner.java:364)at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)at org.testng.TestNG.runSuitesSequentially(TestNG.java:1187)at org.testng.TestNG.runSuitesLocally(TestNG.java:1116)at org.testng.TestNG.runSuites(TestNG.java:1028)at org.testng.TestNG.run(TestNG.java:996)at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)]]>
            </full-stacktrace>
          </exception> <!-- java.lang.Throwable -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- test_to_edit_contacts_sql_query -->
        <test-method status="SKIP" signature="test_to_delete_contacts_sql_query()[pri:0, instance:email_module_test_cases.MaropostEmailContactsTestCases@161b062a]" name="test_to_delete_contacts_sql_query" duration-ms="0" started-at="2018-05-08T17:57:13Z" depends-on-methods="email_module_test_cases.MaropostEmailContactsTestCases.test_to_edit_contacts_sql_query" finished-at="2018-05-08T17:57:13Z">
          <exception class="java.lang.Throwable">
            <message>
              <![CDATA[Method MaropostEmailContactsTestCases.test_to_delete_contacts_sql_query()[pri:0, instance:email_module_test_cases.MaropostEmailContactsTestCases@161b062a] depends on not successfully finished methods]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.Throwable: Method MaropostEmailContactsTestCases.test_to_delete_contacts_sql_query()[pri:0, instance:email_module_test_cases.MaropostEmailContactsTestCases@161b062a] depends on not successfully finished methodsat org.testng.internal.Invoker.invokeTestMethods(Invoker.java:878)at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)at org.testng.TestRunner.privateRun(TestRunner.java:648)at org.testng.TestRunner.run(TestRunner.java:505)at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)at org.testng.SuiteRunner.run(SuiteRunner.java:364)at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)at org.testng.TestNG.runSuitesSequentially(TestNG.java:1187)at org.testng.TestNG.runSuitesLocally(TestNG.java:1116)at org.testng.TestNG.runSuites(TestNG.java:1028)at org.testng.TestNG.run(TestNG.java:996)at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)]]>
            </full-stacktrace>
          </exception> <!-- java.lang.Throwable -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- test_to_delete_contacts_sql_query -->
        <test-method status="SKIP" signature="test_create_new_contacts_preference_page()[pri:0, instance:email_module_test_cases.MaropostEmailContactsTestCases@161b062a]" name="test_create_new_contacts_preference_page" duration-ms="0" started-at="2018-05-08T17:57:13Z" depends-on-methods="email_module_test_cases.MaropostEmailContactsTestCases.test_to_delete_contacts_sql_query" finished-at="2018-05-08T17:57:13Z">
          <exception class="java.lang.Throwable">
            <message>
              <![CDATA[Method MaropostEmailContactsTestCases.test_create_new_contacts_preference_page()[pri:0, instance:email_module_test_cases.MaropostEmailContactsTestCases@161b062a] depends on not successfully finished methods]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.Throwable: Method MaropostEmailContactsTestCases.test_create_new_contacts_preference_page()[pri:0, instance:email_module_test_cases.MaropostEmailContactsTestCases@161b062a] depends on not successfully finished methodsat org.testng.internal.Invoker.invokeTestMethods(Invoker.java:878)at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)at org.testng.TestRunner.privateRun(TestRunner.java:648)at org.testng.TestRunner.run(TestRunner.java:505)at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)at org.testng.SuiteRunner.run(SuiteRunner.java:364)at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)at org.testng.TestNG.runSuitesSequentially(TestNG.java:1187)at org.testng.TestNG.runSuitesLocally(TestNG.java:1116)at org.testng.TestNG.runSuites(TestNG.java:1028)at org.testng.TestNG.run(TestNG.java:996)at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)]]>
            </full-stacktrace>
          </exception> <!-- java.lang.Throwable -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- test_create_new_contacts_preference_page -->
        <test-method status="SKIP" signature="test_to_edit_contacts_preference_page()[pri:0, instance:email_module_test_cases.MaropostEmailContactsTestCases@161b062a]" name="test_to_edit_contacts_preference_page" duration-ms="0" started-at="2018-05-08T17:57:13Z" depends-on-methods="email_module_test_cases.MaropostEmailContactsTestCases.test_create_new_contacts_preference_page" finished-at="2018-05-08T17:57:13Z">
          <exception class="java.lang.Throwable">
            <message>
              <![CDATA[Method MaropostEmailContactsTestCases.test_to_edit_contacts_preference_page()[pri:0, instance:email_module_test_cases.MaropostEmailContactsTestCases@161b062a] depends on not successfully finished methods]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.Throwable: Method MaropostEmailContactsTestCases.test_to_edit_contacts_preference_page()[pri:0, instance:email_module_test_cases.MaropostEmailContactsTestCases@161b062a] depends on not successfully finished methodsat org.testng.internal.Invoker.invokeTestMethods(Invoker.java:878)at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)at org.testng.TestRunner.privateRun(TestRunner.java:648)at org.testng.TestRunner.run(TestRunner.java:505)at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)at org.testng.SuiteRunner.run(SuiteRunner.java:364)at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)at org.testng.TestNG.runSuitesSequentially(TestNG.java:1187)at org.testng.TestNG.runSuitesLocally(TestNG.java:1116)at org.testng.TestNG.runSuites(TestNG.java:1028)at org.testng.TestNG.run(TestNG.java:996)at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)]]>
            </full-stacktrace>
          </exception> <!-- java.lang.Throwable -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- test_to_edit_contacts_preference_page -->
        <test-method status="SKIP" signature="test_to_delete_contacts_preference_page()[pri:0, instance:email_module_test_cases.MaropostEmailContactsTestCases@161b062a]" name="test_to_delete_contacts_preference_page" duration-ms="0" started-at="2018-05-08T17:57:13Z" depends-on-methods="email_module_test_cases.MaropostEmailContactsTestCases.test_to_edit_contacts_preference_page" finished-at="2018-05-08T17:57:13Z">
          <exception class="java.lang.Throwable">
            <message>
              <![CDATA[Method MaropostEmailContactsTestCases.test_to_delete_contacts_preference_page()[pri:0, instance:email_module_test_cases.MaropostEmailContactsTestCases@161b062a] depends on not successfully finished methods]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.Throwable: Method MaropostEmailContactsTestCases.test_to_delete_contacts_preference_page()[pri:0, instance:email_module_test_cases.MaropostEmailContactsTestCases@161b062a] depends on not successfully finished methodsat org.testng.internal.Invoker.invokeTestMethods(Invoker.java:878)at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)at org.testng.TestRunner.privateRun(TestRunner.java:648)at org.testng.TestRunner.run(TestRunner.java:505)at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)at org.testng.SuiteRunner.run(SuiteRunner.java:364)at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)at org.testng.TestNG.runSuitesSequentially(TestNG.java:1187)at org.testng.TestNG.runSuitesLocally(TestNG.java:1116)at org.testng.TestNG.runSuites(TestNG.java:1028)at org.testng.TestNG.run(TestNG.java:996)at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)]]>
            </full-stacktrace>
          </exception> <!-- java.lang.Throwable -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- test_to_delete_contacts_preference_page -->
        <test-method status="PASS" signature="tearDown()[pri:0, instance:email_module_test_cases.MaropostEmailContactsTestCases@161b062a]" name="tearDown" is-config="true" duration-ms="997" started-at="2018-05-08T17:57:14Z" finished-at="2018-05-08T17:57:15Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDown -->
      </class> <!-- email_module_test_cases.MaropostEmailContactsTestCases -->
    </test> <!-- Default test -->
  </suite> <!-- Default suite -->
</testng-results>
